"""Add filed in AuthUser role

Revision ID: dda4589b618e
Revises: 1c5281d61214
Create Date: 2025-10-28 23:37:11.325289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda4589b618e'
down_revision: Union[str, Sequence[str], None] = '1c5281d61214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('role', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_users', 'role')
    # ### end Alembic commands ###
